# Prod
services:
  db:
    image: ghcr.io/${REPOSITORY_OWNER:-andrei-shendrik}/ratan-sun-db:${PROJECT_VERSION:-latest}
    restart: always
    env_file:
      - .env
    # портов нет
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${APP_DB_USER} -d ${APP_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  broker:
    image: redis:8.8-alpine
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  cache:
    image: redis:8.8-alpine
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # cli
  bin2fits-fast-1-3-nodb:
    image: ghcr.io/${REPOSITORY_OWNER:-andrei-shendrik}/ratan-sun-bin2fits-fast-1-3ghz-nodb:${PROJECT_VERSION:-latest}
    restart: "no" # контейнер должен исчезнуть после выполнения задачи
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    env_file:
      - .env
    environment:
      - TZ=${TZ:-Europe/Moscow}
      - FAST_ACQ_1_3GHZ_BIN_ARCHIVE=/data/obs/ratan-600/fast-acquisition-1-3ghz/raw
      - FAST_ACQ_1_3GHZ_FITS_ARCHIVE=/data/obs/ratan-600/fast-acquisition-1-3ghz/fits
      - BIN2FITS_FAST_ACQ_1_3GHZ_NODB_LOG_DIR=/app/logs/ratan-sun/bin2fits-fast-1-3-nodb
    volumes:
      - ${FAST_ACQ_1_3GHZ_BIN_ARCHIVE}:/data/obs/ratan-600/fast-acquisition-1-3ghz/raw
      - ${FAST_ACQ_1_3GHZ_FITS_ARCHIVE}:/data/obs/ratan-600/fast-acquisition-1-3ghz/fits
      - ${BIN2FITS_FAST_ACQ_1_3GHZ_NODB_LOG_DIR}:/app/logs/ratan-sun/bin2fits-fast-1-3-nodb
    # нет command, докер использует дефолтный из Dockerfile (CMD ["--help"])
    # профиль "cli", чтобы этот контейнер игнорировался при "docker compose up -d"
    profiles:
      - cli

  migrator:
    image: ghcr.io/${REPOSITORY_OWNER:-andrei-shendrik}/ratan-sun-backend:${PROJECT_VERSION:-latest}
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    env_file: [ ".env" ]
    environment:
      - DB_HOST=db
      - TZ=${TZ:-Europe/Moscow}
      - BACKEND_LOG_DIR=/app/logs/ratan-sun/backend
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ${BACKEND_LOG_DIR}:/app/logs/ratan-sun/backend
    command: [ "python", "manage.py", "migrate", "--noinput" ]
    restart: "no"

  # wsgi gunicorn
  backend:
    image: ghcr.io/${REPOSITORY_OWNER:-andrei-shendrik}/ratan-sun-backend:${PROJECT_VERSION:-latest}
    restart: always
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - TZ=${TZ:-Europe/Moscow}
      - BACKEND_LOG_DIR=/app/logs/ratan-sun/backend
      - FAST_ACQ_1_3GHZ_BIN_ARCHIVE=/data/obs/ratan-600/fast-acquisition-1-3ghz/raw
      - FAST_ACQ_1_3GHZ_FITS_ARCHIVE=/data/obs/ratan-600/fast-acquisition-1-3ghz/fits
      - FAST_ACQ_1_3GHZ_JSON_DATA=/data/derived/json/web/ratan-600/fast-acquisition-1-3ghz
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_healthy
      cache:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    volumes:
      # прокидывание путей
      - ${BACKEND_LOG_DIR}:/app/logs/ratan-sun/backend
      - ${FAST_ACQ_1_3GHZ_BIN_ARCHIVE}:/data/obs/ratan-600/fast-acquisition-1-3ghz/raw:ro
      - ${FAST_ACQ_1_3GHZ_FITS_ARCHIVE}:/data/obs/ratan-600/fast-acquisition-1-3ghz/fits
      - ${FAST_ACQ_1_3GHZ_JSON_DATA}:/data/derived/json/web/ratan-600/fast-acquisition-1-3ghz
    # запуск через Gunicorn на порту 8000
    command: [ "gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:8000" ]
#    command: >
#      sh -c "uv run python src/manage.py migrate &&
#             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
      
  # celery: исполнитель
  data-worker:
    image: ghcr.io/${REPOSITORY_OWNER:-andrei-shendrik}/ratan-sun-backend:${PROJECT_VERSION:-latest}
    restart: always
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    env_file: [ ".env" ]
    environment:
      - DB_HOST=db
      - TZ=${TZ:-Europe/Moscow}
      - BACKEND_LOG_DIR=/app/logs/ratan-sun/backend
      - FAST_ACQ_1_3GHZ_BIN_ARCHIVE=/data/obs/ratan-600/fast-acquisition-1-3ghz/raw
      - FAST_ACQ_1_3GHZ_FITS_ARCHIVE=/data/obs/ratan-600/fast-acquisition-1-3ghz/fits
      - FAST_ACQ_1_3GHZ_JSON_DATA=/data/derived/json/web/ratan-600/fast-acquisition-1-3ghz
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_healthy
      cache:
        condition: service_healthy
    volumes:
      - ${BACKEND_LOG_DIR}:/app/logs/ratan-sun/backend
      - ${FAST_ACQ_1_3GHZ_BIN_ARCHIVE}:/data/obs/ratan-600/fast-acquisition-1-3ghz/raw:ro
      - ${FAST_ACQ_1_3GHZ_FITS_ARCHIVE}:/data/obs/ratan-600/fast-acquisition-1-3ghz/fits
      - ${FAST_ACQ_1_3GHZ_JSON_DATA}:/data/derived/json/web/ratan-600/fast-acquisition-1-3ghz
    # переопределение команды запуска celery
    # command: ["uv", "run", "celery", "-A", "config", "worker", "-l", "info", "-c", "4"] # для однопоточного убрать ', "-c", "4"'
    command: ["celery", "-A", "config", "worker", "-l", "info", "-c", "4"]

  # celery: beat планировщик (генерация задач и передача исполнителю)
  task-scheduler:
    image: ghcr.io/${REPOSITORY_OWNER:-andrei-shendrik}/ratan-sun-backend:${PROJECT_VERSION:-latest}
    restart: always
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    env_file: [ ".env" ]
    environment:
      - DB_HOST=db
      - TZ=${TZ:-Europe/Moscow}
      - BACKEND_LOG_DIR=/app/logs/ratan-sun/backend
      - FAST_ACQ_1_3GHZ_BIN_ARCHIVE=/data/obs/ratan-600/fast-acquisition-1-3ghz/raw
      - FAST_ACQ_1_3GHZ_FITS_ARCHIVE=/data/obs/ratan-600/fast-acquisition-1-3ghz/fits
      - FAST_ACQ_1_3GHZ_JSON_DATA=/data/derived/json/web/ratan-600/fast-acquisition-1-3ghz
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_healthy
    volumes:
      - ${BACKEND_LOG_DIR}:/app/logs/ratan-sun/backend
      - ${FAST_ACQ_1_3GHZ_BIN_ARCHIVE}:/data/obs/ratan-600/fast-acquisition-1-3ghz/raw:ro
      - ${FAST_ACQ_1_3GHZ_FITS_ARCHIVE}:/data/obs/ratan-600/fast-acquisition-1-3ghz/fits
      - ${FAST_ACQ_1_3GHZ_JSON_DATA}:/data/derived/json/web/ratan-600/fast-acquisition-1-3ghz
    # command: [ "uv", "run", "celery", "-A", "config", "beat", "-l", "info" ]
    command: ["celery", "-A", "config", "beat", "-l", "info"]

#
#  nginx-web:
#    # todo изменить на image
#    build:
#      context: .
#      dockerfile: nginx/Dockerfile
#    restart: always
#    ports:
#      - "80:80"
#      - "443:443"
#    depends_on:
#      - backend
#    volumes:
#      - ${FAST_ACQ_1_3GHZ_JSON_DATA}:/app/data/json/ratan-600/fast-acquisition-1-3ghz:ro # режим Read Only (ro)

  frontend:
    image: ghcr.io/${REPOSITORY_OWNER:-andrei-shendrik}/ratan-sun-frontend:${PROJECT_VERSION:-latest}
    restart: always
    depends_on:
      - backend
    ports:
      - "127.0.0.1:8080:80" # привязка 8080 только к localhost, чтобы снаружи никто не мог обойти Apache

volumes:
  pgdata: