version: '3'

tasks:
  check-deps:
    desc: "Check dependencies"
    cmds:
      - uv run deptry apps/bin2fits-fast-acquisition-1-3ghz/src
      - uv run deptry apps/obs-processor/src
      - uv run deptry libs/ratanpy/src

  up:
    desc: "Power up all containers"
    cmds:
      - docker compose up -d

  down:
    desc: "Stop and remove containers"
    cmds:
      - docker compose down

  build:
    desc: "Rebuild containers"
    cmds:
      - docker compose build

#  test-lib:
#    desc: "Run tests ratanpy"
#    cmds:
#      - uv run pytest libs/ratanpy/tests/