#!/bin/bash
set -e

DB_TO_CONNECT="${POSTGRES_DB:-$POSTGRES_USER}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$DB_TO_CONNECT" <<-EOSQL
    CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASSWORD';
    CREATE DATABASE $APP_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $APP_DB_NAME TO $APP_DB_USER;

    \c $APP_DB_NAME
    GRANT ALL ON SCHEMA public TO $APP_DB_USER;
EOSQL