server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Если файл не найден, отдаем index.html (Standard SPA behavior)
        try_files $uri $uri/ /index.html;
    }
}