"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import logging
import os
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# ./ backend/ src/
BASE_DIR = Path(__file__).resolve().parent.parent

# ./ backend/
BACKEND_DIR = BASE_DIR.parent

# added .env path: /ratan-sun /apps /backend
ROOT_DIR = BASE_DIR.parent.parent.parent
ENV_PATH = ROOT_DIR / '.env'

load_dotenv(ENV_PATH)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-mg5cw!1)au7kdaivpfe*4y_lc$xz6xdl2&k44jz=o+x3u&48e$'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured("CRITICAL ERROR: DJANGO_SECRET_KEY environment variable is missing")

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False # True
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() == 'true'

# ALLOWED_HOSTS = []
allowed_hosts_env = os.environ.get('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost')
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(',')]

# настройка доверенных источников для CSRF
csrf_trusted_env = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', 'http://127.0.0.1,http://localhost')
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_trusted_env.split(',')]

# настройка SSL Proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'observations',
    'users'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['APP_DB_NAME'],
        'USER': os.environ['APP_DB_USER'],
        'PASSWORD': os.environ['APP_DB_PASSWORD'],
        'HOST': os.environ['DB_HOST'],
        'PORT': os.environ['DB_PORT'],
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_TZ = True # True = БД хранит в UTC, отображает в соответствии с TIME_ZONE

"""
TIME_ZONE влияет только на представление, хранение будет в соответствии с USE_TZ. 
USE_TZ = True значит хранить в UTC. 
TIME_ZONE = 'Europe/Moscow' заставит django admin показывать время мск
Если TIME_ZONE = UTC, то представление времени ложится на клиента
"""
TIME_ZONE = 'UTC' # 'Europe/Moscow'

USE_I18N = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# чтобы не путать с static фронтенда
STATIC_URL = 'django-static/' # 'static/'

# папка, куда команда collectstatic соберет все файлы
STATIC_ROOT = BACKEND_DIR / 'staticfiles'

# кэширование whitenoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]

# авторизация по email
AUTH_USER_MODEL = 'users.CustomUser'

# после разделения на cache и broker переменная REDIS_HOST не нужна
# windows default: localhost, prod: переменная REDIS_HOST
# REDIS_HOST = os.environ.get('REDIS_HOST', 'localhost')

# CELERY_BROKER_URL = f'redis://{REDIS_HOST}:6379/0'
# CELERY_RESULT_BACKEND = f'redis://{REDIS_HOST}:6379/0'
# # CELERY_TIMEZONE = 'Europe/Moscow' # 'UTC'
#
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': f'redis://{os.environ.get("REDIS_HOST", "localhost")}:6379/1', # использование БД №1 для кэша (для celery БД №0)
#     }
# }

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0') # дефолт (localhost:6379) только для pycharm

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.environ.get('CACHE_URL', 'redis://localhost:6380/1'), # дефолт (localhost:6380) только для pycharm
    }
}

# логирование
BACKEND_LOG_DIR = Path(os.environ.get('BACKEND_LOG_DIR', BASE_DIR / 'logs'))
BACKEND_LOG_DIR.mkdir(parents=True, exist_ok=True)
BACKEND_LOG_LEVEL = os.environ.get('BACKEND_LOG_LEVEL') # ('BACKEND_LOG_LEVEL', 'INFO')

# celery будет использовать настройки логов django
CELERY_WORKER_HIJACK_ROOT_LOGGER = False
CELERY_TIMEZONE = 'Europe/Moscow'

LOG_TIME_ZONE = 'Europe/Moscow'

# форматтер логов
class LocalTimeFormatter(logging.Formatter):
    def formatTime(self, record, datefmt=None):
        dt = datetime.fromtimestamp(record.created, tz=ZoneInfo("UTC"))
        # конвертация в часовой пояс, заданный в ОС (через docker-compose TZ)
        # если переменной нет, fallback на мск
        # local_tz = os.environ.get('TZ', 'Europe/Moscow')
        # dt_local = dt.astimezone(ZoneInfo(local_tz))
        dt_local = dt.astimezone(ZoneInfo(LOG_TIME_ZONE))

        if datefmt:
            return dt_local.strftime(datefmt)
        return dt_local.isoformat()

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            '()': LocalTimeFormatter, # '()' = класс находится прямо здесь
            'format': '[{asctime}] [{levelname}] [{module}] {message}',
            # 'format': '[{asctime}] [{levelname}] [{name}] {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file_debug': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BACKEND_LOG_DIR / 'debug.log',
            'maxBytes': 10 * 1024 * 1024, # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
            'level': 'DEBUG',
        },
        'file_info': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BACKEND_LOG_DIR / 'info.log',
            'maxBytes': 10 * 1024 * 1024, # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
            'level': 'INFO',
        },
        'file_warning': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BACKEND_LOG_DIR / 'warning.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
            'level': 'WARNING',
        },
        'file_error': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BACKEND_LOG_DIR / 'error.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
            'level': 'ERROR',
        },
        'file_critical': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BACKEND_LOG_DIR / 'critical.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
            'level': 'CRITICAL',
        },
    },
    'loggers': {
        # логи самого django
        'django': {
            'handlers': ['console', 'file_info', 'file_warning', 'file_error', 'file_critical'],
            'level': 'WARNING',
            'propagate': False,
        },
        # логи observations
        'observations': {
            'handlers': ['console', 'file_debug', 'file_info', 'file_warning', 'file_error', 'file_critical'],
            'level': BACKEND_LOG_LEVEL,
            'propagate': False,
        },
        # системные логи celery
        'celery': {
            'handlers': ['console', 'file_debug', 'file_info', 'file_warning', 'file_error', 'file_critical'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# CELERY_BEAT_SCHEDULE = {
#     'monitor-fast-acq-1-3ghz-raw-every-minute': {
#         'task': 'observations.tasks.fast_acquisition_1_3ghz.beat_fast_acq_1_3ghz_monitor_raw_archive',
#         'schedule': 10.0,
#     },
#     'dispatch-fast-acq-1-3ghz-jobs-every-minute': {
#         'task': 'observations.tasks.fast_acquisition_1_3ghz.beat_fast_acq_1_3ghz_dispatch_jobs',
#         'schedule': 10.0,
#     },
# }