# Generated by Django 6.0.7 on 2026-07-09 20:17

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawObservationFastAcquisition1To3GHz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('relative_path', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('object_of_observation', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('azimuth', models.FloatField(blank=True, db_index=True, null=True)),
                ('obs_start_utc', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('datetime_obs_utc', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('obs_stop_utc', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Raw observation FastAcquisition 1-3 GHz',
                'verbose_name_plural': 'Raw observations FastAcquisition 1-3 GHz',
                'db_table': 'raw_observation_fast_acquisition_1_3ghz',
                'ordering': ['-datetime_obs_utc'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingJobBin2FitsFastAcquisition1To3GHz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('unprocessed', 'Unprocessed'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='unprocessed', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('peak_memory_mb', models.FloatField(blank=True, db_index=True, null=True)),
                ('time_taken_sec', models.FloatField(blank=True, db_index=True, null=True)),
                ('min_free_ram_gb', models.FloatField(blank=True, help_text='Override .env value', null=True)),
                ('max_worker_ram_gb', models.FloatField(blank=True, help_text='Override .env value', null=True)),
                ('raw_observation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_bin2fits', to='observations.rawobservationfastacquisition1to3ghz')),
            ],
            options={
                'verbose_name': 'Processing Job Bin2Fits FastAcquisition 1-3 GHz',
                'verbose_name_plural': 'Processing Jobs Bin2Fits FastAcquisition 1-3 GHz',
                'db_table': 'processing_job_bin2fits_fast_acquisition_1_3ghz',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FitsObservationFastAcquisition1To3GHz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('relative_path', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('object_of_observation', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('azimuth', models.FloatField(blank=True, db_index=True, null=True)),
                ('obs_start_utc', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('datetime_obs_utc', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('obs_stop_utc', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('datetime_culmination_efrat_utc', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('datetime_culmination_feed_horn_utc', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('obs_mode', models.CharField(blank=True, choices=[('regular', 'Regular'), ('tracking', 'Tracking'), ('scanning', 'Scanning')], max_length=20, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('declination', models.FloatField(blank=True, null=True)),
                ('right_ascension', models.FloatField(blank=True, null=True)),
                ('solar_r', models.FloatField(blank=True, null=True)),
                ('solar_p', models.FloatField(blank=True, null=True)),
                ('solar_b', models.FloatField(blank=True, null=True)),
                ('scan_angle', models.FloatField(blank=True, null=True)),
                ('data_values', models.CharField(blank=True, choices=[('lr', 'LHCP, RHCP'), ('iv', 'Stokes I, Stokes V')], max_length=2, null=True)),
                ('pol_chan0', models.CharField(blank=True, choices=[('lhcp', 'Left Hand Circular Polarization'), ('rhcp', 'Right Hand Circular Polarization'), ('stokes_i', 'Stokes I'), ('stokes_v', 'Stokes V')], max_length=10, null=True)),
                ('pol_chan1', models.CharField(blank=True, choices=[('lhcp', 'Left Hand Circular Polarization'), ('rhcp', 'Right Hand Circular Polarization'), ('stokes_i', 'Stokes I'), ('stokes_v', 'Stokes V')], max_length=10, null=True)),
                ('num_samples', models.IntegerField(blank=True, null=True)),
                ('num_frequencies', models.IntegerField(blank=True, null=True)),
                ('ref_time', models.FloatField(blank=True, help_text='seconds from the start of registration', null=True)),
                ('ref_sample', models.IntegerField(blank=True, null=True)),
                ('samples_per_second', models.FloatField(blank=True, null=True)),
                ('arcsec_per_sample', models.FloatField(blank=True, null=True)),
                ('arcsec_per_second', models.FloatField(blank=True, null=True)),
                ('record_duration_seconds', models.FloatField(blank=True, null=True)),
                ('time_reduction_factor', models.FloatField(blank=True, null=True)),
                ('frequency_resolution', models.FloatField(blank=True, null=True)),
                ('time_resolution', models.FloatField(blank=True, null=True)),
                ('arcsec_resolution', models.FloatField(blank=True, null=True)),
                ('switch_polarization_time', models.FloatField(blank=True, null=True)),
                ('feed_horn_offset', models.FloatField(blank=True, null=True)),
                ('feed_horn_offset_time', models.FloatField(blank=True, null=True)),
                ('attenuator_common', models.FloatField(blank=True, null=True)),
                ('attenuator_1_2ghz', models.FloatField(blank=True, null=True)),
                ('attenuator_2_3ghz', models.FloatField(blank=True, null=True)),
                ('half_width_kurtosis_interval', models.FloatField(blank=True, null=True)),
                ('is_bad', models.BooleanField(blank=True, default=False, null=True)),
                ('is_calibrated', models.BooleanField(blank=True, default=False, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('quiet_sun_point_arcsec', models.FloatField(blank=True, null=True)),
                ('raw_observation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fits_observation', to='observations.rawobservationfastacquisition1to3ghz')),
            ],
            options={
                'verbose_name': 'Fits observation FastAcquisition 1-3 GHz',
                'verbose_name_plural': 'Fits observations FastAcquisition 1-3 GHz',
                'db_table': 'fits_observation_fast_acquisition_1_3ghz',
                'ordering': ['-datetime_culmination_feed_horn_utc'],
            },
        ),
        migrations.CreateModel(
            name='VisualizationFitsFastAcquisition1To3GHz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('json_relative_path', models.CharField(help_text='Relative path from *WEB_DATA root', max_length=500)),
                ('json_filename', models.CharField(max_length=255, unique=True)),
                ('thumbnail_relative_path', models.CharField(help_text='Relative path from *WEB_DATA root', max_length=500)),
                ('thumbnail_filename', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('spectrogram_num_freqs', models.IntegerField()),
                ('spectrogram_num_samples', models.IntegerField()),
                ('scan_group_num_freqs', models.IntegerField()),
                ('scan_group_num_samples', models.IntegerField()),
                ('fits_observation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visualization_fits', to='observations.fitsobservationfastacquisition1to3ghz')),
            ],
            options={
                'verbose_name': 'Visualization Fits FastAcquisition 1-3 GHz',
                'verbose_name_plural': 'Visualization Fits FastAcquisition 1-3 GHz',
                'db_table': 'visualization_fits_fast_acquisition_1_3ghz',
                'ordering': ['-updated_at'],
            },
        ),
    ]
