# Generated by Django 6.0.6 on 2026-07-05 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processingjobbin2fitsfastacquisition1to3ghz',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Processing Job Bin2Fits FastAcquisition 1-3 GHz', 'verbose_name_plural': 'Processing Jobs Bin2Fits FastAcquisition 1-3 GHz'},
        ),
    ]
