# Определение файлов, подлежащих обработке
[file_filters]
allowed_patterns = [
    '(?i)^\d{4}-\d{2}-\d{2}_\d{6}_sun[+-]?\d{1,2}\.bin(\.gz)?$'
]
forbidden_patterns = [
    '(?i)AR'
]

# visualization
[visualization.spectrogram]
frequencies = 512
samples = 1000

[visualization.scan_group]
frequencies = 50
samples = 1000

# превью-картинки (webp)
[visualization.thumbnail]
width_px = 800
height_px = 450