# Generated by Django 6.0.5 on 2026-06-17 00:12

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawObservationFastAcquisition1To3GHzDB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bin_path_filename', models.CharField(max_length=500, unique=True)),
                ('bin_filename', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'verbose_name': 'Raw observation FastAcquisition 1-3GHz',
                'verbose_name_plural': 'Raw observations FastAcquisition 1-3GHz',
                'db_table': 'raw_observation_fast_acquisition_1_3ghz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingJobBin2FitsFastAcquisition1To3GHzDB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('unprocessed', 'Unprocessed'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='unprocessed', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('min_free_ram_gb', models.FloatField(blank=True, help_text='Override .env value', null=True)),
                ('max_worker_ram_gb', models.FloatField(blank=True, help_text='Override .env value', null=True)),
                ('peak_memory_mb', models.FloatField(blank=True, null=True)),
                ('time_taken_sec', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('raw_observation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing_job_bin2fits_fast_1_3', to='observations.rawobservationfastacquisition1to3ghzdb')),
            ],
            options={
                'verbose_name': 'Processing Job Bin2Fits FastAcquisition 1-3GHz',
                'verbose_name_plural': 'Processing Jobs Bin2Fits FastAcquisition 1-3GHz',
                'db_table': 'processing_job_bin2fits_fast_acquisition_1_3ghz',
            },
        ),
        migrations.CreateModel(
            name='FitsObservationFastAcquisition1To3GHzDB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fits_path_filename', models.CharField(max_length=500)),
                ('fits_filename', models.CharField(max_length=255, unique=True)),
                ('telescope', models.CharField(max_length=100)),
                ('observation_object', models.CharField(db_index=True, max_length=100)),
                ('azimuth', models.FloatField(db_index=True)),
                ('datetime_reg_start_utc', models.DateTimeField()),
                ('datetime_reg_start_local', models.DateTimeField()),
                ('datetime_culmination_efrat_utc', models.DateTimeField()),
                ('datetime_culmination_efrat_local', models.DateTimeField()),
                ('datetime_culmination_feed_horn_utc', models.DateTimeField(db_index=True)),
                ('datetime_culmination_feed_horn_local', models.DateTimeField()),
                ('datetime_reg_stop_utc', models.DateTimeField()),
                ('datetime_reg_stop_local', models.DateTimeField()),
                ('altitude', models.FloatField()),
                ('declination', models.FloatField()),
                ('right_ascension', models.FloatField()),
                ('solar_radius', models.FloatField()),
                ('solar_position_angle', models.FloatField()),
                ('solar_b_angle', models.FloatField()),
                ('data_values', models.CharField(choices=[('lr', 'LHCP, RHCP'), ('iv', 'Stokes I, Stokes V')], max_length=2)),
                ('pol_ch0', models.CharField(choices=[('lhcp', 'Left Hand Circular Polarization'), ('rhcp', 'Right Hand Circular Polarization'), ('stokes_i', 'Stokes I'), ('stokes_v', 'Stokes V')], max_length=10)),
                ('pol_ch1', models.CharField(choices=[('lhcp', 'Left Hand Circular Polarization'), ('rhcp', 'Right Hand Circular Polarization'), ('stokes_i', 'Stokes I'), ('stokes_v', 'Stokes V')], max_length=10)),
                ('num_samples', models.IntegerField()),
                ('num_frequencies', models.IntegerField()),
                ('ref_time', models.FloatField(help_text='seconds from the start of registration')),
                ('ref_sample', models.IntegerField()),
                ('start_pulse_edge_sample', models.IntegerField()),
                ('start_pulse_edge_time', models.FloatField()),
                ('stop_pulse_edge_sample', models.IntegerField()),
                ('stop_pulse_edge_time', models.FloatField()),
                ('samples_per_second', models.FloatField()),
                ('arcsec_per_sample', models.FloatField()),
                ('arcsec_per_second', models.FloatField()),
                ('record_duration_seconds', models.FloatField()),
                ('time_reduction_factor', models.FloatField()),
                ('frequency_resolution', models.FloatField()),
                ('time_resolution', models.FloatField()),
                ('arcsec_resolution', models.FloatField()),
                ('switch_polarization_time', models.FloatField()),
                ('feed_horn_offset', models.FloatField()),
                ('feed_horn_offset_time', models.FloatField()),
                ('attenuator_common', models.FloatField()),
                ('attenuator_1_2ghz', models.FloatField()),
                ('attenuator_2_3ghz', models.FloatField()),
                ('half_width_kurtosis_interval', models.FloatField()),
                ('is_bad', models.BooleanField(default=False)),
                ('is_calibrated', models.BooleanField(default=False)),
                ('unit', models.CharField(max_length=50)),
                ('quiet_sun_point_arcsec', models.FloatField()),
                ('data_receiver', models.CharField(max_length=100)),
                ('band', models.CharField(max_length=100)),
                ('freq_min', models.FloatField()),
                ('freq_max', models.FloatField()),
                ('json_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('raw_observation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fits_observation_fast_1_3', to='observations.rawobservationfastacquisition1to3ghzdb')),
            ],
            options={
                'verbose_name': 'Fits observation FastAcquisition 1-3GHz',
                'verbose_name_plural': 'Fits observations FastAcquisition 1-3GHz',
                'db_table': 'fits_observation_fast_acquisition_1_3ghz',
                'ordering': ['-datetime_culmination_feed_horn_utc'],
            },
        ),
    ]
