name: Production deploy on solar server (manual start)

on:
  workflow_dispatch: # триггер workflow_dispatch запуск скрипта вручную кнопкой в GitHub
    inputs:
      version:
        description: 'Version tag to deploy (e.g., v1.0.1)'
        required: true
        default: 'latest'

jobs:
  build-and-push:
    runs-on: ubuntu-latest # ОС внутри самого гитхаб
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version }} # код конкретного тега

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Django
#      - name: Build and push Django API
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          file: ./apps/djangoapi/Dockerfile
#          push: true
#          tags: ghcr.io/${{ github.repository_owner }}/myproject-djangoapi:${{ github.event.inputs.version }}

      # Аналогично React
      # ...

  deploy-to-server:
    needs: build-and-push # Ждем, пока соберутся образы
    runs-on: ubuntu-latest
    steps:
      - name: SSH to Production and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /main/ratan-sun

            # Логиним сервер в твой GitHub Registry, чтобы он мог скачать приватные образы
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # поиск в файле .env строки, которая начинается с PROJECT_VERSION= 
            # замена ее на новый git-тег.
            # если переменной там нет, добавление в конец файла
            if grep -q "^PROJECT_VERSION=" .env; then
              sed -i "s/^PROJECT_VERSION=.*/PROJECT_VERSION=${{ github.event.inputs.version }}/" .env
            else
              echo "PROJECT_VERSION=${{ github.event.inputs.version }}" >> .env
            fi

            # скачивание новых собранных образов
            docker compose pull

            # перезапуск контейнеров
            docker compose up -d --remove-orphans