name: Production deploy on solar server (manual start)

on:
  workflow_dispatch: # триггер workflow_dispatch запуск скрипта вручную кнопкой в GitHub
    inputs:
      version:
        description: 'Version tag to deploy (e.g., v1.0.1)'
        required: true
        default: 'latest'

jobs:
  build-and-push:
    runs-on: ubuntu-latest # ОС внутри самого гитхаб
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.inputs.version }} # код конкретного тега

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push database image
        uses: docker/build-push-action@v7
        with:
          context: ./infra/postgres
          file: ./infra/postgres/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ratan-sun-db:${{ github.event.inputs.version }}
            ghcr.io/${{ github.repository_owner }}/ratan-sun-db:latest

      - name: Build and push bin2fits-fast-1-3-nodb image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: apps/bin2fits-fast-acquisition-1-3ghz-nodb/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ratan-sun-bin2fits-fast-1-3-nodb:${{ github.event.inputs.version }}
            ghcr.io/${{ github.repository_owner }}/ratan-sun-bin2fits-fast-1-3-nodb:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ratan-sun-bin2fits-fast-1-3-nodb:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ratan-sun-bin2fits-fast-1-3-nodb:buildcache,mode=max

      - name: Build and push frontend image
        uses: docker/build-push-action@v7
        with:
          context: ./apps/frontend
          file: ./apps/frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ratan-sun-frontend:${{ github.event.inputs.version }}
            ghcr.io/${{ github.repository_owner }}/ratan-sun-frontend:latest
          # кэширование для ускорения сборки npm
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ratan-sun-frontend:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ratan-sun-frontend:buildcache,mode=max

      - name: Build and push backend image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./apps/backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ratan-sun-backend:${{ github.event.inputs.version }}
            ghcr.io/${{ github.repository_owner }}/ratan-sun-backend:latest
          # кэширование
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ratan-sun-backend:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ratan-sun-backend:buildcache,mode=max

  deploy-to-server:
    needs: build-and-push # ожидание пока соберутся образы
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Copy docker-compose and infrastructure to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.yml, infra/postgres/init-db.sh"
          target: "/main/ratan-sun"

      - name: SSH to Production and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /main/ratan-sun
            
            chmod +x infra/postgres/init-db.sh

            # логин сервера GitHub Registry для скачивания образов
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # 1. Обновление/запись PROJECT_VERSION в .env
            # поиск в файле .env строки, которая начинается с PROJECT_VERSION= замена ее на новый git-тег.
            # если переменной там нет, добавление в конец файла            
            TARGET_VERSION="${{ github.event.inputs.version }}"
            if ! grep -q "^PROJECT_VERSION=${TARGET_VERSION}$" .env; then
              if grep -q "^PROJECT_VERSION=" .env; then
                sed -i "s/^PROJECT_VERSION=.*/PROJECT_VERSION=${TARGET_VERSION}/" .env
              else
                echo "PROJECT_VERSION=${TARGET_VERSION}" >> .env
              fi
              echo "Updated PROJECT_VERSION to ${TARGET_VERSION}"
            fi
            
            # 2. Обновление/запись REPOSITORY_OWNER
            # приведение к нижнему регистру     
            OWNER_LOWERCASE=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
            if ! grep -q "^REPOSITORY_OWNER=${OWNER_LOWERCASE}$" .env; then
              if grep -q "^REPOSITORY_OWNER=" .env; then
                sed -i "s/^REPOSITORY_OWNER=.*/REPOSITORY_OWNER=${OWNER_LOWERCASE}/" .env
              else
                echo "REPOSITORY_OWNER=${OWNER_LOWERCASE}" >> .env
              fi
              echo "Updated REPOSITORY_OWNER to ${OWNER_LOWERCASE}"
            fi

            # скачивание новых собранных образов
            docker compose pull

            # перезапуск контейнеров
            docker compose up -d --remove-orphans